---

extends: default

rules:
  line-length: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  indentation: disable

ignore: |
  lovelace-ui.yaml
  custom_components/
  .git
  .github
  themes/
  esphome/