language: python
python:
  - "3.7.3"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
sudo: required
before_install:
  - then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - then sudo apt-get update; fi
  - then sudo apt-get install -y ffmpeg; fi
  - mv dummy_secrets.yaml secrets.yaml
