language: python
python:
  - "3.7.3"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
os: linux
dist: xenial
before_install:
  - pip3 install netdisco
  - pip3 install home-assistant-frontend
  - mv dummy_secrets.yaml secrets.yaml