language: python
python:
  - "3.7.3"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
sudo: required
os: linux
dist: xenial
before_install:
  - then sudo add-apt-repository -y ppa:mc3man/xerus-media;
  - then sudo apt-get update;
  - then sudo apt-get install -y ffmpeg;
  - mv dummy_secrets.yaml secrets.yaml
