- alias: Saugroboter ist fertig
  id: '1544472184317'
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: docked
  condition: []
  action:
  - alias: Notify iOS app
    data:
      message: ' Der Staubsauger ist fertig. in {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time  }}
        min hat er {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area
        }} m² gereinigt. Verbleibende Akkukapazität: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level
        }} %'
      title: ' Saugroboter fertig'
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
- alias: Saugroboter Error
  id: '1544472184318'
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: error
  condition: []
  action:
  - alias: Notify iOS app
    data:
      message: Der Staubsauger hat einen Fehler
      title: Der Staubsauger hat einen Fehler
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
- alias: Wenn keiner zuhause, Licht aus
  id: '1539122857421'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.wohnzimmer_deko_regal
    service: switch.turn_off
  - data:
      entity_id: switch.wohnzimmer_deko_lampions
    service: switch.turn_off
  - data:
      entity_id: switch.flur_switch
    service: switch.turn_off
  - data:
      entity_id: switch.lichtschalterkueche
    service: switch.turn_off
  - data:
      message: Überprüfe, ob der TV zB noch lief und schalte ihn ab!
      title: Alle Lichter Ausgeschaltet, da keiner mehr zuhause
    service: notify.mobile_app
- alias: Starte Saugen durch Abwesenheit
  id: '1544476061506'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  condition:
  - after: 09:00
    before: '21:00'
    condition: time
  - below: '1'
    condition: numeric_state
    entity_id: variable.staubsauger_runcounter
  action:
  - alias: ''
    data: {}
    service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
  - data:
      message: 'Dein Staubsauger fängt jetzt an. Runcounter: {{ states.variable.staubsauger_runcounter.state
        }}'
      title: Staubsauger Startet, da keiner zuhause
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
- alias: 'Saugroboter counter update '
  id: '1544476061523'
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: cleaning
  condition: []
  action:
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
- alias: Staubsauger RunCounter Resetten
  id: '1544565337548'
  trigger:
  - at: '8:50'
    platform: time
  condition: []
  action:
  - data:
      value: '0'
      variable: staubsauger_runcounter
    service: variable.set_variable
- alias: Starte Saugen durch Zeit
  id: '1544910582816'
  trigger:
  - at: '10:30'
    platform: time
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: variable.staubsauger_runcounter
  - condition: state
    entity_id: group.all_devices
    state: not_home
  action:
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
  - data:
      message: 'Dein Staubsauger fängt jetzt an. Runcounter: {{ states.variable.staubsauger_runcounter.state
        }}'
      title: Staubsauger Startet
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
- alias: Fernseher schaltet Dreamscreen an
  id: '1546875168005'
  trigger:
  - entity_id: switch.tv_power
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: dreamscreen.dream_screen
      mode: '1'
    service: dreamscreen.set_mode
- alias: Fernseher schaltet Dreamscreen aus
  id: '1546875223626'
  trigger:
  - entity_id: switch.tv_power
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: dreamscreen.dream_screen
      mode: '0'
    service: dreamscreen.set_mode
- alias: Automatisierungen An
  id: '1547397663898'
  trigger:
  - at: '1:00'
    platform: time
  - at: '8:00'
    platform: time
  - at: '14:00'
    platform: time
  - at: '18:00'
    platform: time
  - at: '18:00'
    platform: time
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_automations
    service: automation.turn_on
- alias: Starte Homekit mit Delay
  id: '1550779173464'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02
  - service: homekit.start
- alias: iPhone Action AllLightsOff
  id: '1550779173465'
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'AllLightsOff '
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.deko_switch
    service: switch.turn_off
  - data:
      entity_id: switch.flur_switch
    service: switch.turn_off
  - data:
      entity_id: switch.lichtschalterkueche
    service: switch.turn_off
- alias: iPhone Action Staubsauger starten
  id: '1550779173466'
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Staubsauger starten
  action:
  - alias: ''
    data: {}
    service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
- alias: iPhone Action Fernseher umschalten
  id: '1550779173467'
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Fernseher umschalten
  action:
  - data:
      entity_id: switch.tv_power
    service: switch.toggle
- alias: Remove new devices notification
  trigger:
  - platform: state
    entity_id: persistent_notification.config_entry_discovery
    to: notifying
  - platform: homeassistant
    event: start
  action:
  - service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery
  id: a287fa7c5e804c07b5d508da93c2ca14
- alias: Weihnachtsdeko abends anschalten
  id: '1575837347767'
  description: Bei Sonnenuntergang die Weihnachtsdeko aktivieren
  trigger:
  - event: sunset
    offset: '-1'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.steckdose_weihnachtsstern
    service: switch.turn_on
- alias: Weihnachtsdeko abends ausschalten
  id: '1575837521534'
  description: ''
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.steckdose_weihnachtsstern
    service: switch.turn_off
- alias: Weihnachtsdeko frueh anschalten
  id: '1575837521535'
  description: ''
  trigger:
  - at: '5:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.steckdose_weihnachtsstern
    service: switch.turn_on
- alias: Weihnachtsdeko früh ausschalten
  id: '1575837347737'
  description: Bei Sonnenuntergang die Weihnachtsdeko ausschalten
  trigger:
  - event: sunrise
    offset: '+1'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.steckdose_weihnachtsstern
    service: switch.turn_off
- alias: Deko abends ausschalten
  id: '1575837347738'
  description: Alle Lampen ausschalten, die der Deko Gruppe zugewiesen sind
  trigger:
    - at: '23:00'
      platform: time
  condition: []
  action:
  - data:
      entity_id: group.dekoration
    service: switch.turn_off
  - data:
      entity_id: group.dekoration
    service: light.turn_off