- id: '1528225019888'
  alias: Wohnzimmer abend Beleuchtung
  trigger:
  - event: sunset
    offset: '-2'
    platform: sun
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.xiaomimia1
      state: home
    - condition: state
      entity_id: device_tracker.oneplus6
      state: home
  action:
  - data:
      entity_id: light.wohnzimmer_2
    service: light.turn_on
- id: '1529021181271'
  alias: 'Bürolich an, wenn PC Nachts an geht '
  trigger:
  - entity_id: device_tracker.ryzenpc
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.buro
    service: light.turn_on
