- id: '1544472184317'
  alias: Saugroboter ist fertig
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: docked
  condition: []
  action:
  - alias: Notify iOS app
    data:
      message: ' Der Staubsauger ist fertig. in {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time  }}
        min hat er {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area
        }} m² gereinigt. Verbleibende Akkukapazität: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level
        }} %'
      title: ' Saugroboter fertig'
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
- id: '1539122857421'
  alias: Wenn keiner zuhause, Licht aus
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.deko_switch
    service: switch.turn_off
  - data:
      entity_id: switch.flur_switch
    service: switch.turn_off
  - data:
      entity_id: switch.lichtschalterkueche
    service: switch.turn_off
  - data:
      message: Überprüfe, ob der TV zB noch lief und schalte ihn ab!
      title: Alle Lichter Ausgeschaltet, da keiner mehr zuhause
    service: notify.mobile_app
- id: '1544476061506'
  alias: Starte Saugen durch Abwesenheit
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  condition:
  - after: 09:00
    before: '21:00'
    condition: time
  - below: '1'
    condition: numeric_state
    entity_id: variable.staubsauger_runcounter
  action:
  - alias: ''
    data: {}
    service: vacuum.start
  - data:
      message: 'Dein Staubsauger fängt jetzt an. Runcounter: {{ states.variable.staubsauger_runcounter.state
        }}'
      title: Staubsauger Startet, da keiner zuhause
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
- id: '1544476061523'
  alias: 'Saugroboter counter update '
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: cleaning
  condition: []
  action:
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
- id: '1544565337548'
  alias: Staubsauger RunCounter Resetten
  trigger:
  - at: '8:50'
    platform: time
  condition: []
  action:
  - data:
      value: '0'
      variable: staubsauger_runcounter
    service: variable.set_variable
- id: '1544910582816'
  alias: Starte Saugen durch Zeit
  trigger:
  - at: '10:30'
    platform: time
  condition:
  - below: '1'
    condition: numeric_state
    entity_id: variable.staubsauger_runcounter
  - condition: state
    entity_id: group.all_devices
    state: not_home
  action:
  - service: vacuum.start
  - data:
      value_template: '{{ (variable.state | int) + 1 }}'
      variable: staubsauger_runcounter
    service: variable.set_variable
  - data:
      message: 'Dein Staubsauger fängt jetzt an. Runcounter: {{ states.variable.staubsauger_runcounter.state
        }}'
      title: Staubsauger Startet
      data:
        push:
          thread-id: vacuum-group
    service: notify.mobile_app
- id: '1546875168005'
  alias: Fernseher schaltet Dreamscreen an
  trigger:
  - entity_id: switch.tv_power
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: dreamscreen.dream_screen
      mode: '1'
    service: dreamscreen.set_mode
- id: '1546875223626'
  alias: Fernseher schaltet Dreamscreen aus
  trigger:
  - entity_id: switch.tv_power
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: dreamscreen.dream_screen
      mode: '0'
    service: dreamscreen.set_mode
- id: '1547397663898'
  alias: Automatisierungen An
  trigger:
  - at: '1:00'
    platform: time
  - at: '8:00'
    platform: time
  - at: '14:00'
    platform: time
  - at: '18:00'
    platform: time
  - at: '18:00'
    platform: time
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_automations
    service: automation.turn_on
- id: '1550779173464'
  alias: Starte Homekit mit Delay
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02
  - service: homekit.start
- id: '1563746340325'
  alias: 'wasserpumpe aus '
  trigger:
  - entity_id: switch.steckdose_bewaesserung
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:03:00
  - data:
      entity_id: switch.steckdose_bewaesserung
    service: switch.turn_off
- id: '1550779173465'
  alias: "iPhone Action AllLightsOff"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'AllLightsOff'
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.deko_switch
    service: switch.turn_off
  - data:
      entity_id: switch.flur_switch
    service: switch.turn_off
  - data:
      entity_id: switch.lichtschalterkueche
    service: switch.turn_off