- id: '1539122857421'
  alias: Wenn keiner zuhause, Licht aus
  trigger:
  - entity_id: device_tracker.j3n50m4t_oneplus6
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.dfa703aa_vanessa
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.dfa703aa_vanessa
    state: not_home
  - condition: state
    entity_id: device_tracker.j3n50m4t_oneplus6
    state: not_home
  action:
  - alias: ''
    data:
      entity_id: group.all_lights
    service: light.turn_off
