- id: '1539122857421'
  alias: Wenn keiner zuhause, Licht aus
  trigger:
  - entity_id: device_tracker.j3n50m4t_oneplus6
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.dfa703aa_vanessa
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.dfa703aa_vanessa
    state: not_home
  - condition: state
    entity_id: device_tracker.j3n50m4t_oneplus6
    state: not_home
  action:
  - alias: ''
    data:
      entity_id: group.all_lights
    service: light.turn_off
- id: '1541885808013'
  alias: wenig Speicher auf Server
  trigger:
  - below: '200'
    entity_id: sensor.sabnzbd_disk_free
    platform: numeric_state
  condition: []
  action:
  - alias: ''
    data:
      message: Server Storage is below 200 GB
      title: Disk Storage on Server
    service: notify.join
- id: '1541885858102'
  alias: Markus Standort enter
  trigger:
  - entity_id: device_tracker.j3n50m4t_oneplus6
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Markus ist zuhause
      title: Standort
    service: notify.join
- id: '1541885858145'
  alias: Markus Standort Leave
  trigger:
  - entity_id: device_tracker.j3n50m4t_oneplus6
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Markus ist nicht mehr zuhause
      title: Standort
    service: notify.join
- id: '1541885858132'
  alias: Vanessa Standort enter
  trigger:
  - entity_id: device_tracker.dfa703aa_vanessa
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Vanessa ist zuhause
      title: Standort
    service: notify.join
- id: '1541866858145'
  alias: Vanessa Standort Leave
  trigger:
  - entity_id: device_tracker.dfa703aa_vanessa
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Vanessa ist nicht mehr zuhause
      title: Standort
    service: notify.join
- id: cleaning_timer_weekdays
  alias: Wochentags
  trigger:
  - platform: template
    value_template: '{{ states.sensor.vacuum_start_time_weekdays.state == states.sensor.time.state
      }}'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
- id: cleaning_timer_weekend
  alias: Wochenende
  trigger:
  - platform: template
    value_template: '{{ states.sensor.vacuum_start_time_weekend.state == states.sensor.time.state
      }}'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
