- alias: Starte Homekit mit Delay
  id: '1550779173464'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:01
  - service: homekit.start
- id: '1602967607387'
  alias: 'Notifiy: Critical Battery iPad'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: a2052b4410a211eb810359ee5277127a
    entity_id: sensor.ipad_von_markus_battery_level
    domain: sensor
    below: 25
  condition: []
  action:
  - service: notify.mobile_app_iphonej3
    data:
      message: 'Der Akku vom iPad ist kritisch. Verbleibende Akkukapazität: {{ states.device_tracker.ipad_von_markus.attributes.battery_level}}
        %'
      title: iPad Akku kritisch!
      data:
        push:
          thread-id: low-battery
  mode: single
- id: '1602968028491'
  alias: 'Notifiy: Critical Battery Op6'
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: b3887cd610b711ebb078dd22a668a37f
    entity_id: sensor.oneplus_a6003_akkustand
    domain: sensor
    below: 15
  condition:
  - type: is_not_plugged_in
    condition: device
    device_id: b3887cd610b711ebb078dd22a668a37f
    entity_id: binary_sensor.oneplus_a6003_ladt_auf
    domain: binary_sensor
  action:
  - service: notify.mobile_app_iphonej3
    data:
      message: 'Der Akku vom OP6 ist kritisch. Verbleibende Akkukapazität: {{ states.sensor.oneplus_a6003_akkustand.state_with_unit
        }}'
      title: OP6 Akku kritisch!
      data:
        push:
          thread-id: low-battery
  mode: single
- id: '1603219342103'
  alias: 'Security: Schalte Steckdose Esszimmer nach 2 h aus'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 19c5976e0f1411eb817865e5a12ec692
    entity_id: switch.steckdose_esszimmer
    domain: switch
  condition: []
  action:
  - type: turn_off
    device_id: 19c5976e0f1411eb817865e5a12ec692
    entity_id: switch.steckdose_esszimmer
    domain: switch
  mode: single
- id: '1603219374222'
  alias: 'Security: Schalte Steckdose Wohnzimmer nach 2 h aus'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e7a059f60f1311ebb7f67b9e67f1af66
    entity_id: switch.steckdose_wohnzimmertuer
    domain: switch
    for:
      hours: 2
      minutes: 0
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: e7a059f60f1311ebb7f67b9e67f1af66
    entity_id: switch.steckdose_wohnzimmertuer
    domain: switch
  mode: single
- id: '1603219401776'
  alias: 'Security: Schalte Steckdose TVBoard nach 2 h aus '
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 969d54160f1411eba0d4a15f453636c9
    entity_id: switch.steckdose_tv_board
    domain: switch
    for:
      hours: 2
      minutes: 0
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 969d54160f1411eba0d4a15f453636c9
    entity_id: switch.steckdose_tv_board
    domain: switch
  mode: single
- id: '1603219427956'
  alias: 'Security: Schalte Steckdose Wickelzimmer nach 2 h aus'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: fbcc42440f1411eba2412965904c83d6
    entity_id: switch.steckdose_wickelzimmer
    domain: switch
    for:
      hours: 2
      minutes: 0
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: fbcc42440f1411eba2412965904c83d6
    entity_id: switch.steckdose_wickelzimmer
    domain: switch
  mode: single
- id: '1603219463242'
  alias: 'Security: Schalte Steckdose Schlafzimmer nach 2 h aus'
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 0b5ac2c90f1511ebb1616768214d53f8
    entity_id: switch.steckdose_schlafzimmer
    domain: switch
    for:
      hours: 2
      minutes: 0
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 0b5ac2c90f1511ebb1616768214d53f8
    entity_id: switch.steckdose_schlafzimmer
    domain: switch
  mode: single
