automation: !include automations.yaml

browser_mod:

camera:
  - platform: generic
    verify_ssl: false
    still_image_url: !secret kinderzimmer_cameraurl_still
    stream_source: !secret kinderzimmer_cameraurl_stream
    name: Kinderzimmer

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

dreamscreen:
  devices:
    - dream_screen:
        address: !secret dreamscreenip
        timeout: 5

frontend: 
  themes: !include_dir_merge_named themes

group: !include groups.yaml

history:

home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

homekit: !include assistants/homekit.yaml

ios:

lock:
  - platform: nuki
    host: !secret nuki_lock_home_host
    token: !secret nuki_lock_home_token

logbook:

logger:
  default: info
  logs:
    homeassistant.core: fatal
    mobile_app: debug
    
lovelace:
  mode: yaml

map:

mobile_app:

mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password
  
recorder:
  purge_keep_days: 30
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor

speedtestdotnet:
  scan_interval:
    minutes: 30

switch: !include_dir_merge_list switch

system_health:

updater:

# Text to speech
tts:
  - platform: google_translate
