automation: !include automations.yaml

config:

device_tracker: !include device_tracker.yaml
  
discovery:

frontend:

group:
#group: !include groups.yaml

habitica:
  - api_user: !secret habitica_api_user
    api_key: !secret habitica_api_key
    name: !secret habitica_name

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password 

logbook:

map:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor
  
shiftr:
  username: !secret shiftr_username 
  password: !secret shiftr_password
sun:

tts:
  - platform: google

tradfri:
  host: !secret tradfri_host
  
updater:

zone: !include zone.yaml




