automation: !include automations.yaml

cloud: 
  alexa:
    filter:
      include_entities:
        - switch.tv_power
        - switch.lichtschalterkueche
        - light.wohnzimmer
        - light.esszimmer
        - light.kinderzimmer
        - light.schlafzimmer
        - light.stehlampe
        - light.yeelight_rgb_34ce008e9873
      exclude_domains:
        - alert
        - automation
        - cover
        - fan
        - group
        - input_boolean
        - light
        - lock
        - media_player
        - scene
        - script
        - switch
    entity_config:
      switch.lichtschalterkueche:
        name: Küchenleiste
        description: Leiste unter den Schränken in der Küche
        display_categories: LIGHT
      switch.tv_power:
        name: Fernseher
        description: Fernseher
        display_categories: TV
      light.wohnzimmer:
        name: Wohnzimmer
      light.esszimmer:
        name: Esszimmer
      light.kinderzimmer:
        name: Kinderzimmer
      light.schlafzimmer:
        name:  Schlafzimmer
      light.stehlampe:
        name:  Stehlampe
      light.yeelight_rgb_34ce008e9873
        name: Küche
config:

device_tracker: !include device_tracker.yaml
  
discovery:

frontend:

# group:
group: !include groups.yaml

habitica:
  - api_user: !secret habitica_api_user
    api_key: !secret habitica_api_key
    name: !secret habitica_name

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password 

light:
  - platform: yeelight
    devices:
      !secret yeelight_kueche_ip:
        name: Küche
        transition: 1000

logbook:

map:

media_player:
  - platform: cast

panel_iframe:
  configurator:
    title: FileEditor
    icon: mdi:wrench
    url: http://hassio.local:3218

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch  
shiftr:
  username: !secret shiftr_username 
  password: !secret shiftr_password
sun:

tts:
  - platform: google

tradfri:
  host: !secret tradfri_host
  
updater:

zone: !include zone.yaml




