homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  # customize: !include customize.yaml
    

frontend:
config:
http:
  api_password: !secret homeassistant_http_password

updater:
conversation:
recorder:
history:
logbook:
map:
sun:

shiftr:
  username: !secret shiftr_username
  password: !secret shiftr_password
