air_quality:
  - platform: opensensemap
    station_id: !secret opensense_id

automation: !include automations.yaml
alexa: !include assistants/alexa.yaml
  
camera: 
  - platform: mjpeg
    mjpeg_url: !secret cameraurl
  - platform: local_file
    name: Grafana_fritzbox_traffic
    file_path: /config/www/grafanaimages/fritzboxtraffic.png
  - platform: local_file
    name: Grafana_tvboard_temperature
    file_path: /config/www/grafanaimages/tvboardtemp.png

config:

device_tracker: !include device_tracker.yaml

discovery:


dreamscreen:
  ip_adress: !secret dreamscreenip
  
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-aftership.html


# group:
group: !include groups.yaml

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config
    
homekit:
  auto_start: false
  filter:
    include_entities:
      - light.wohnzimmer
      - light.esszimmer_2
      - light.hintergrundbeleuchtung
      - light.schlafzimmer
      - group.kuchenlichter
      - group.wohnkuchelichter
      - switch.tv_power
      - switch.deko_switch
      - switch.steckdose_deko

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password

influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_username
  password: !secret influx_password
  include:
    domains:
      - sensor

ios:

light:
  - platform: yeelight
  - platform: flux_led
    automatic_add: false
    devices: 
      192.168.1.21:
        name: Hintergrundbeleuchtung
        mode: "rgb"

logbook:

lovelace:
  mode: yaml

map:

mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password

n26:
  username: !secret n26_email
  password: !secret n26_password

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl

recorder: 
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

script: !include scripts.yaml
        
sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

sun:

system_health:

updater:

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip_adress
    token: !secret vacuum_token
    
variable:
  staubsauger_runcounter:
    value: 0
    attributes:
      icon: mdi:robot-vacuum
      
weather: 
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: hourly
    name: Wetter

zone: !include zone.yaml
