homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
frontend:
config:
http:
  api_password: !secret homeassistant_http_password

updater:
conversation:
recorder:

history:
logbook:

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  client_id: !secret mqtt_client_id 
#  username: !secret mqtt_username
#  password: !secret mqtt_password

discovery: 
  
tradfri:
  host: !secret tradfri_host_ip
  allow_tradfri_groups: false

map:
sun:
sensor: !include_dir_merge_list sensors
device_tracker: !include_dir_merge_list device_tracker
media_player: !include_dir_merge_list media_player
switch: !include_dir_merge_list switch
#android_ip_webcam: !include_dir_merge_list android_ip_webcam ## not active
light: !include_dir_merge_list light  

group: !include groups.yaml
automation: !include automations.yaml