# android_ip_webcam:
#   - host: 192.168.1.131
#     name: Op3

automation: !include automations.yaml
alexa:
  smart_home:
    filter:
      include_entities:
        - group.kuchenlichter
        - group.wohnkuchelichter
        - light.esszimmer
        - light.fenstee
        - light.kinderzimmer
        - light.hintergrundbeleuchtung
        - light.mitte
        - light.schlafzimmer
        - light.stehlampe
        - light.wohnung
        - light.woodbox
        - light.yeelight_rgb_34ce008e9873
        - switch.anlage_power
        - switch.deko_switch
        - switch.lichtschalterkueche
        - switch.tv_power
      exclude_domains:
        - alert
        - automation
        - cover
        - fan
        - group
        - input_boolean
        - light
        - lock
        - media_player
        - scene
        - script
        - switch
    entity_config:
      group.kuchenlichter:
        name: Küche
        description: Alle Lichter in der Küche
        display_categories: LIGHT
      group.wohnkuchelichter:
        name: Wohnküche
        description: Alle Lichter im Wohnzimmer Esszimmer und Küche
        display_categories: LIGHT
      light.esszimmer:
        name: Esszimmer
      light.fenstee:
        name: WohnzimmerFenster
      light.kinderzimmer:
        name: Kinderzimmer
      light.hintergrundbeleuchtung:
        name: Hintergrundbeleuchtung
        display_categories: LIGHT
      light.mitte:
        name: WohnzimmerMitte
      light.schlafzimmer:
        name:  Schlafzimmer
      light.stehlampe:
        name:  Stehlampe
      light.wohnung:
        name: WohnzimmerWohnung
      light.woodbox:
        name: Woodbox
      light.yeelight_rgb_34ce008e9873:
        name: Küchenlampe
      switch.deko_switch:
        name: Deko
        description: Dekoration im Haus
        display_categories: LIGHT
      switch.anlage_power:
        name: Stereoanlage
        display_categories: Speaker
      switch.lichtschalterkueche:
        name: Küchenleiste
        description: Leiste unter den Schränken in der Küche
        display_categories: LIGHT
      switch.tv_power:
        name: Fernseher
        description: Fernseher
        display_categories: TV

config:

device_tracker: !include device_tracker.yaml

discovery:

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-aftership.html


# group:
group: !include groups.yaml

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password

ios:

joaoapps_join:
  - api_key: !secret join_api_key
    device_id: group.all
    name: Alle Geräte

light:
  - platform: yeelight
    devices:
      !secret yeelight_kueche_ip:
        name: Küche
        transition: 1000
  - platform: flux_led
    automatic_add: false
    devices: 
      192.168.1.233:
        name: Hintergrundbeleuchtung
        mode: "rgb"
      192.168.1.33:
        name: Woodbox
        mode: "rgb"
        
    

logbook:

map:

media_player:


mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password

notify:
  - platform: joaoapps_join
    api_key: join_api_key
    device_id: group.all
    name: All

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl

sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

sun:

tts:
  - platform: google

tradfri:
  host: !secret tradfri_host

updater:

weather: 
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: hourly
    name: Wetter

zone: !include zone.yaml
