airly:

alexa: !include assistants/alexa.yaml

api:

automation: !include automations.yaml

camera:
  - platform: generic
    verify_ssl: false
    still_image_url: !secret kinderzimmer_cameraurl_still
    stream_source: !secret kinderzimmer_cameraurl_stream
    name: Kinderzimmer

config:

device_tracker: !include device_tracker.yaml

discovery:
  ignore:
    - apple_tv
    - belkin_wemo
    - bluesound
    - bose_soundtouch
    - denonavr
    - directv
    - enigma2
    - frontier_silicon
    - google_cast
    - harmony
    - igd
    - logitech_mediaserver
    - netgear_router
    - octoprint
    - openhome
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - sabnzbd
    - samsung_printer
    - samsung_tv
    - sonos
    - songpal
    - tellstick
    - wink
    - yamaha
    - yeelight
    - xiaomi_gw

dreamscreen:
  devices:
    - dream_screen:
        address: !secret dreamscreenip
        timeout: 5
frontend:


# group:
group: !include groups.yaml

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url

homekit: !include assistants/homekit.yaml
  
ios:

life360:
  driving_speed: 39
  interval_seconds: 10
  prefix: life360
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3
  accounts:
    - username: !secret LIFE360_USERNAME
      password: !secret LIFE360_PASSWORD

light:
  - platform: yeelight


logbook:

logger:
  default: critical
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for SmartThings lights
    homeassistant.components.fritzbox_netmonitor: debug

lovelace:
  mode: yaml

map:

mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password

# Removed due to 403. see python_n26
# n26:
#   username: !secret n26_email
#   password: !secret n26_password

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl

person: !include person.yaml

recorder:
  purge_keep_days: 15
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor

speedtestdotnet: 

switch: !include_dir_merge_list switch

sun:

system_health:

updater: 

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip_adress
    token: !secret vacuum_token

variable:
  staubsauger_runcounter:
    value: 0
    attributes:
      icon: mdi:robot-vacuum

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: hourly
    name: Wetter

yeelight:
  devices:
    !secret yeelight_kitchen:
      name: Küchenlicht
      
zone: !include zone.yaml
