# android_ip_webcam:
#   - host: 192.168.1.131
#     name: Op3

automation: !include automations.yaml
alexa: !include assistants/alexa.yaml
  
camera: 
  - platform: mjpeg
    mjpeg_url: !secret cameraurl

config:

device_tracker: !include device_tracker.yaml

discovery:

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-aftership.html


# group:
group: !include groups.yaml

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password

input_number: !include input_number.yaml

ios:


joaoapps_join:
  - api_key: !secret join_api_key
    device_id: group.all
    name: Alle Geräte

light:
  - platform: yeelight
    devices:
      !secret yeelight_kueche_ip:
        name: Küche
        transition: 1000
  - platform: flux_led
    automatic_add: false
    devices: 
      192.168.1.233:
        name: Hintergrundbeleuchtung
        mode: "rgb"
      192.168.1.33:
        name: Woodbox
        mode: "rgb"
        
    

logbook:

map:

media_player:


mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password

notify: 
  - platform: joaoapps_join
    api_key: !secret join_api_key
    device_id: !secret join_device_id_op6 
    name: Join
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl

sabnzbd:
  api_key: !secret sabnzb_api_key
  host: !secret sabnzb_host
  ssl: true
  port: 443
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size  

script: 
  find_vacuum:
    alias: Find Vacuum
    sequence:
      - service: vacuum.locate
        entity_id:
        - vacuum.xiaomi_vacuum_cleaner
        
sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

sun:

tts:
  - platform: google

tradfri:
  host: !secret tradfri_host

updater:

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip_adress
    token: !secret vacuum_token

wake_on_lan:
  mac: !secret ryzenpc_mac
weather: 
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: hourly
    name: Wetter

zone: !include zone.yaml
