automation: !include automations.yaml

browser_mod:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

dreamscreen:
  devices:
    - dream_screen:
        address: !secret dreamscreenip
        timeout: 5

frontend: 
  themes: !include_dir_merge_named themes

group: !include groups.yaml

history:

ios:

lock:
  - platform: nuki
    host: !secret nuki_lock_home_host
    token: !secret nuki_lock_home_token

logbook:

logger:
  default: info
  logs:
    homeassistant.core: fatal
    mobile_app: debug
    
lovelace:
  mode: yaml

map:

mobile_app:

mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password
  
recorder:
  purge_keep_days: 30
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

scene: !include scenes.yaml

script: !include scripts.yaml

system_health:

# Text to speech
tts:
  - platform: google_translate
