automation: !include automations.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml

lovelace:
  mode: yaml

scene: !include scenes.yaml

script: !include scripts.yaml

# Text to speech
tts:
  - platform: google_translate
