alexa: !include assistants/alexa.yaml

api:

automation: !include automations.yaml

camera:
  - platform: generic
    verify_ssl: false
    still_image_url: !secret schlafzimmer_cameraurl_still
    stream_source: !secret schlafzimmer_cameraurl_stream
    name: schlafzimmer
  - platform: local_file
    name: Grafana_fritzbox_traffic
    file_path: /config/www/grafanaimages/fritzboxtraffic.png
  - platform: local_file
    name: Grafana_tvboard_temperature
    file_path: /config/www/grafanaimages/tvboardtemp.png

config:

device_tracker: !include device_tracker.yaml

# igd is for upnp
discovery:
  ignore:
    - google_cast
    - igd
    - yeelight

dreamscreen:
  devices:
    - dream_screen:
        address: !secret dreamscreenip
        timeout: 5
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-aftership.html


# group:
group: !include groups.yaml

history:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

http:
  base_url: !secret http_base_url
homekit:
  auto_start: false
    
influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_username
  password: !secret influx_password
  include:
    domains:
      - sensor

ios:

light:
  - platform: yeelight

logbook:

lovelace:
  mode: yaml

map:

mqtt:
  broker: !secret mqtt_domain
  username: !secret mqtt_user
  password: !secret mqtt_password

n26:
  username: !secret n26_email
  password: !secret n26_password

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl

person: !include person.yaml

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor

stream:

switch: !include_dir_merge_list switch

sun:

system_health:

updater: 

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip_adress
    token: !secret vacuum_token

variable:
  staubsauger_runcounter:
    value: 0
    attributes:
      icon: mdi:robot-vacuum

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: hourly
    name: Wetter

yeelight:
  devices:
    !secret yeelight_kitchen:
      name: Küchenlicht
      
zone: !include zone.yaml
