# - platform: fritz
#   host : 192.168.1.1
#   username: !secret device_tracker_fritz_username
#   password: !secret device_tracker_fritz_password
# - platform: owntracks
  # max_gps_accuracy: 200
- platform: traccar