- platform: fritz
  host : 192.168.1.1
  username: !secret device_tracker_fritz_username
  password: !secret device_tracker_fritz_password
  interval_seconds: 30
  consider_home: 300
  new_device_defaults:
    track_new_devices: false
    hide_if_away: true