title: Home
views:
  - title: Home
    cards:
      - type: entities
        title: Wohnzimmer
        show_header_toggle: true
        entities:
          - light.wohnung
          - light.fenstee
          - light.mitte
      - type: entities
        title: "Küche"
        show_header_toggle: true
        entities:
          - light.kuche
          - switch.lichtschalterkueche
      - type: entities
        title: "Wohnküche"
        show_header_toggle: true
        entities:
          - light.esszimmer
          - light.fenstee
          - light.kuche
          - light.mitte
          - light.wohnung
          - light.woodbox
          - switch.deko_switch
          - switch.lichtschalterkueche
      - type: weather-forecast
        name: Wetter
        entity: weather.openweathermap
      - type: map
        entities: 
          - device_tracker.j3n50m4t_oneplus6
          - device_tracker.dfa703aa_vanessa
          - zone.home
          aspect_ratio: 70%
          default_zoom: 11