resources:
  - url: /local/custom_ui/custom-lovelace/monster-card/monster-card.js
    type: js    
  - url: /local/custom_ui/state-attribute-element/state-attribute-element.js
    type: js
  - url: /local/custom_ui/text-element/text-element.js
    type: js
  - url: /local/custom_ui/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /local/custom_ui/xiaomi_vacuum_map_card/dist/xiaomi-vacuum-map-card.js
    type: module
    
title: Zuhause
views: !include_dir_list lovelace/views/
  