title: Zuhause
views:
  - title: Home
    cards:
      - type: weather-forecast
        name: Wetter
        entity: weather.openweathermap
      - type: conditional
        conditions:
          - entity: device_tracker.j3n50m4t_oneplus6 
            state_not: "home"
        card:
          type: map
          entities: 
            - device_tracker.j3n50m4t_oneplus6
            - device_tracker.dfa703aa_vanessa
            - zone.home
          aspect_ratio: 70%
          default_zoom: 11
      - type: conditional
        conditions:
          - entity: device_tracker.dfa703aa_vanessa 
            state_not: "home"
        card:
          type: map
          entities: 
            - device_tracker.j3n50m4t_oneplus6
            - device_tracker.dfa703aa_vanessa
            - zone.home
          aspect_ratio: 70%
          default_zoom: 11
      - type: entities
        title: "Wohnküche"
        show_header_toggle: true
        entities:
          - light.esszimmer
          - light.fenstee
          - light.kuche
          - light.mitte
          - light.wohnung
          - light.woodbox
          - switch.deko_switch
          - switch.lichtschalterkueche
      - type: entities
        title: Wohnzimmer
        show_header_toggle: true
        entities:
          - light.wohnung
          - light.fenstee
          - light.mitte
      - type: entities
        title: "Küche"
        show_header_toggle: true
        entities:
          - light.kuche
          - switch.lichtschalterkueche
      - type: sensor
        entity: sensor.speedtest_download
        name: Downloadspeed
        height: 75
        line_color: "#3498db"
        icon: mdi:speedometer
        unit: Mbit/s
      - type: sensor
        entity: sensor.plex_serien
        name: Serien
        height: 75
        line_color: "#3498db"
        icon: mdi:youtube-tv
        unit: Folgen
        hours_to_show: 168