resources: 
  - url: /hacsfiles/weather-card/weather-card.js 
    type: module
  - url: /hacsfiles/lovelace-floorplan/floorplan-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
    
title: Home
views: !include_dir_list lovelace/views/