resources:
  - url: /local/custom_ui/state-card-aftership.js
    type: js

title: Zuhause
views:
  - title: Home
    cards:
      - type: weather-forecast
        name: Wetter
        entity: weather.openweathermap
      - type: conditional
        conditions:
          - entity: device_tracker.j3n50m4t_oneplus6 
            state_not: "home"
        card:
          type: map
          entities: 
            - device_tracker.j3n50m4t_oneplus6
            - device_tracker.dfa703aa_vanessa
            - zone.home
          aspect_ratio: 70%
          default_zoom: 11
      - type: conditional
        conditions:
          - entity: device_tracker.dfa703aa_vanessa 
            state_not: "home"
        card:
          type: map
          entities: 
            - device_tracker.j3n50m4t_oneplus6
            - device_tracker.dfa703aa_vanessa
            - zone.home
          aspect_ratio: 70%
          default_zoom: 11
      - type: glance 
        title: Steuereinheit
        entities:
          - light.esszimmer
          - switch.deko_switch
          - group.kuchenlichter
          - group.wohnzimmerlichter
      - type: sensor
        entity: sensor.speedtest_download
        name: Downloadspeed
        height: 75
        line_color: "#3498db"
        icon: mdi:speedometer
        unit: Mbit/s
      - type: "custom:state-card-aftership-ll"
        entity: sensor.aftership_sensor 
        icon: mdi:cube-send
        name: Sendeverfolgung
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.pihole_ads_blocked_today
            name: Blocked Today
            height: 75
            line_color: "#ff0000"
            hours_to_show: 168
            accuracy: 7
            unit: blocks
          - type: sensor
            entity: sensor.pihole_ads_percentage_blocked_today
            name: Percentage Today
            height: 75
            line_color: "#ff0000"
            hours_to_show: 168
            accuracy: 7
            unit: Percent
          - type: sensor
            entity: sensor.pihole_dns_queries_today
            name: Queries Today
            height: 75
            line_color: "#2f2c7f"
            hours_to_show: 168
            accuracy: 7
            unit: Queries
