resources:
  - url: /local/custom_ui/custom-lovelace/monster-card/monster-card.js
    type: js    
  - url: /local/custom_ui/state-attribute-element/state-attribute-element.js
    type: js
  - url: /local/custom_ui/text-element/text-element.js
    type: js
  - url: /local/custom_ui/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
    
title: Zuhause
views:
  - title: Home
    cards:
      - type: weather-forecast
        entity: weather.wetter
      - type: iframe
        url: !secret windyurl
        aspect_ratio: 100%
      - type: map
        aspect_ratio: 100%
        entities:
          - !secret person_sensor_person_one
          - !secret person_sensor_person_two
          - zone.home
          - zone.arbeit
      - type: custom:monster-card
        show_empty: false
        card: 
          type: entities
          title: Allgemeine Schalter
        filter:
          include: 
            - entity_id: "light.esszimmer"
            - entity_id: "light.kuchenlicht"
            - entity_id: "light.leuchtkugel"
            - entity_id: "light.stehlampe"
            - entity_id: "group.wohnzimmerlichter"
            - entity_id: "switch.deko_switch"
            - entity_id: "switch.steckdose_bewaesserung"
            - entity_id: "switch.lichtschalterkueche"
            - entity_id: "switch.flur_switch"
            - entity_id: "switch.tv_power"
          exclude: 
      - type: entity-filter
        entities:
          - !secret person_sensor_person_one
          - !secret person_sensor_person_two
        state_filter:
          - home
        card: 
          type: glance
          title: Wer ist zuhause
  - title: Markus
    cards: 
      - type: map
        aspect_ratio: 100%
        default_zoom: 11
        entities:
          - !secret person_sensor_person_one
      - type: glance
        title: Phonestate
        entities:
          - entity: sensor.person_one_battery
            icon: mdi:battery-30
          - entity: sensor.person_one_wifi
            icon: mdi:wifi
          - entity: sensor.person_one_gps
            icon: mdi:crosshairs-gps
       - type: glance
        title: Money
        entities:
          - entity: !secret konto_eins
            icon: mdi:cash
          - entity: !secret konto_zwei
            icon: mdi:cash
             

  - title: Wohnküche
    cards:
      - type: entities
        entities:
          - group.wohnzimmerlichter
          - light.esszimmer
          - group.kuchenlichter
          - switch.deko_switch
          - type: divider
          - light.wohnung
          - light.fenster
          - light.mitte
      - type: vertical-stack
        cards: 
          - type: glance
            title: Fernseher
            show_state: false
            columns: 3
            entities:
            - entity: switch.tv_power
              icon: mdi:power
              name:
              tap_action: 
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.tv_power
            - entity: switch.tv_volume
              icon: mdi:volume-minus
              name:
              tap_action: 
                action: call-service
                service: switch.turn_off
                service_data:
                  entity_id: switch.tv_volume
            - entity: switch.tv_volume
              icon: mdi:volume-plus
              name:
              tap_action: 
                action: call-service
                service: switch.turn_on
                service_data:
                  entity_id: switch.tv_volume    
      - type: vertical-stack
        cards: 
          - type: glance
            title: Dreamscreen Source
            show_state: false
            columns: 3
            entities:
              - entity: dreamscreen.dream_screen
                icon: mdi:youtube-tv
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_hdmi_source
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    source: "0"
              - entity: dreamscreen.dream_screen
                icon: mdi:xbox
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_hdmi_source
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    source: "1"
              - entity: dreamscreen.dream_screen
                icon: mdi:steam
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_hdmi_source
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    source: "2"
      - type: vertical-stack
        cards: 
          - type: glance
            title: Dreamscreen Mode
            show_state: false
            columns: 3
            entities:
              - entity: dreamscreen.dream_screen
                icon: mdi:power
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_mode
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    mode: "0"
              - entity: dreamscreen.dream_screen
                icon: mdi:television
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_mode
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    mode: "1"
              - entity: dreamscreen.dream_screen
                icon: mdi:alarm-light
                name:
                tap_action:
                  action: call-service
                  service: dreamscreen.set_mode
                  service_data:
                    entity_id: dreamscreen.dream_screen
                    mode: "3"
 
  - title: Monitoring
    cards:
      - type: sensor
        entity: sensor.tv_board_temperature
        name: TV Board Temperatur
        height: 75
        line_color: "#3498db"
        icon: mdi:oil-temperature
        unit: °C

  - title: Cams
    icon: mdi:cctv
    cards: 
      - type: picture-entity
        name: Schlafzimmer
        entity: camera.schlafzimmer
        camera_image: camera.schlafzimmer

  - title: Tautulli card
    icon: mdi:plex
    cards:
      - type: picture-elements
        image: /local/images/plex.jpg
        elements: 
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Now Playing: </b>"
            style:
              top: 7%
              left: 15px
              transform: none
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Statistics: </b>"
            style:
              top: 37%
              left: 15px
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "Top Movie"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 5px'>Most played movie: </b>"
            style:
              top: 50%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "Top TV Show"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 11px'>Most played show: </b>"
            style:
              top: 60%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "Top User"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 20px'>Most active user: </b>"
            style:
              top: 70%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "stream_count"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 20px'>Current Streams: </b>"
            style:
              top: 80%
              left: 15px
              color: white
              transform: none              
  - title: Automatisierung
    cards: 
      - type: vertical-stack
        cards:
          - type: picture-elements
            image: https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/8/2/8249fd50a958e80bd226584a09acd534471bbb4a.png
            elements:
            - type: icon
              icon: mdi:bell-ring
              tap_action: 
                action: call-service
                service: vacuum.locate
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 65%
                "--paper-item-icon-color": rgb(115, 122, 130)
            - type: icon
              tap_action: 
                action: call-service
                service: vacuum.return_to_base
              entity: vacuum.xiaomi_vacuum_cleaner
              icon: mdi:home
              style:
                top: 90%
                left: 55%
                "--paper-item-icon-color": rgb(115, 122, 130)
            - type: icon
              icon: mdi:play
              tap_action: 
                action: call-service
                service: vacuum.start
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 45%
                "--paper-item-icon-color": rgb(115, 122, 130)
            - type: icon
              icon: mdi:stop
              tap_action: 
                action: call-service
                service: vacuum.stop
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 35%
                "--paper-item-icon-color": rgb(115, 122, 130)
            - type: state-label
              entity: sensor.vacuum_operation
              style:
                top: 10%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-color: rgb(34, 154, 210)
                background-color: rgb(54, 65, 78)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_accessories
              style:
                top: 10%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-color: rgb(34, 154, 210)
                background-color: rgb(54, 65, 78)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_main_brush
              style:
                top: 30%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_side_brush
              style:
                top: 45%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_filter
              style:
                top: 60%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_sensor
              style:
                top: 75%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_status
              style:
                top: 30%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_battery
              style:
                top: 45%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_area_cleaned
              style:
                top: 60%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_cleaning_time
              style:
                top: 75%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                text-shadow: 1px 1px black
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8        

      - type: entities
        entities:
          - group.all_automations
          - automation.fernseher_schaltet_dreamscreen_an
          - automation.fernseher_schaltet_dreamscreen_aus
          - automation.saugroboter_counter_update
          - automation.saugroboter_ist_fertig
          - automation.starte_saugen_durch_abwesenheit
          - automation.starte_saugen_durch_zeit
          - automation.staubsauger_runcounter_resetten
          - automation.wenn_keiner_zuhause_licht_aus   