- platform: yeelight
  devices:
    !secret yeelight_arbeitszimmer:
      name: Arbeitsraum
      transition: 1000
      use_music_mode: false #(defaults to False)
      save_on_change: True #(defaults to True)
