- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  switches: 
    lichtschalterkueche:
      friendly_name: "Küchenleiste"
      command_on: !secret broadlink_steckdose_kueche_licht_command_on
      command_off: !secret broadlink_steckdose_kueche_licht_command_off
    steckdose_weihnachtsstern:
      friendly_name: "Wohnzimmer Weihnachtsdeko Stern"
      command_on: !secret broadlink_steckdose_2_command_on
      command_off: !secret broadlink_steckdose_2_command_off
    tv_volume:
      friendly_name: "Fernseher Volume"
      command_on: !secret broadlink_ir_tv_volume_command_on
      command_off: !secret broadlink_ir_tv_volume_command_off
    tv_power:
      friendly_name: "Fernseher"
      command_on: !secret broadlink_ir_tv_power_command_on
      command_off: !secret broadlink_ir_tv_power_command_off
    tv_input:
        friendly_name: "Fernseher Input"
        command_on: !secret broadlink_ir_tv_input_command_on
        command_off: !secret broadlink_ir_tv_input_command_off

    anlage_volume:
      friendly_name: "Stereoanlage Volume"
      command_on: !secret broadlink_ir_stereoanlage_volume_command_on
      command_off: !secret broadlink_ir_stereoanlage_volume_command_off
    anlage_power:
      friendly_name: "Stereoanlage"
      command_on: !secret broadlink_ir_stereoanlage_power_command_on
      command_off: !secret broadlink_ir_stereoanlage_power_command_off
    Lichtschild:
      friendly_name: "Lichtschild"
      command_on: !secret broad_link_codes_brennstuhl_a_command_on
      command_off: !secret broad_link_codes_brennstuhl_a_command_off



