- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - wind_speed
    - temperature_max
    - temperature_min
    - temperature