- platform: deluge
  host: !secret synology_host
  username: !secret deluge_username
  password: !secret deluge_password
  name: SynologyDeluge
  monitored_variables:
    - 'download_speed'
    - 'upload_speed'