- platform: sabnzbd
  host: !secret sabnzbd_server
  port: 8090
  api_key: d1b1e1231c771689dc0d96a9f637ad53
  monitored_variables:
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_free'
    - 'queue_count'