- platform: scrape
  resource: "http://www.clever-tanken.de/tankstelle_details/823"
  name: jetloebtauer
  select: '#main-content-fuel-price-list'
  value_template: '{{ value.split("-")[5] }}'
  unit_of_measurement: '€'

- platform: scrape
  resource: "http://www.clever-tanken.de/tankstelle_details/2194"
  name: starcoventry
  select: '#main-content-fuel-price-list'
  value_template: '{{ value.split("-")[5] }}'
  unit_of_measurement: '€'
  
- platform: scrape
  resource: "http://www.clever-tanken.de/tankstelle_details/19060"
  name: kauflandfreiberg
  select: '#main-content-fuel-price-list'
  value_template: '{{ value.split("-")[5] }}'
  unit_of_measurement: '€'
