- platform: synologydsm
  host: !secret synology_host
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
