- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  origin: !secret google_travel_time_origin
  destination: !secret google_travel_time_destination
  travelmode: driving
  options: 
    language: de