- platform: synologydsm
  host: !secret synology_ip
  username: !secret synology_username
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_down
    - network_up
    - disk_smart_status
    - volume_percentage_used
