- platform: template
  sensors:
    oneplus6_battery:
    friendly_name: OP6 von Markus
    unit_of_measurement: "%"
    value_template: '{{ states.device_tracker.markus_oneplus6.attributes.battery|int }}'
    device_class: battery