- platform: template
  sensors:
    anzahl_scrobbles:
      friendly_name: "Anzahl Scrobbles"
      unit_of_measurement: 'Anzahl'
      value_template: "{{ states.sensor.lastfm_j3n50m4t.attributes.play_count }}"