esphome:
  name: flurlicht
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifiname
  password: !secret wifipassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flurlicht"
    password: "xHesBgXq7YG7"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret espaccesspassword

ota:
  password: !secret espaccesspassword
