esphome:
  name: flurlicht
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifiname
  password: !secret wifipassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flurlicht"
    password: "xHesBgXq7YG7"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret espaccesspassword

ota:
  password: !secret espaccesspassword
  

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    id: floor_binary  
    on_press:
      then:
        - light.turn_on: floor_light
    on_release:
      then:
        - light.turn_off: floor_light
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        - switch.turn_on: floor_light_restart

  - platform: status
    name: "Flurlicht Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "Flurlicht"
    id: floor_light
    output: relay_1
    
switch:
  - platform: restart
    name: "Reboot floor Sonoff"
    id: floor_light_restart


status_led:
  pin:
    number: GPIO13
    inverted: yes
