---
name: Homeassistant Test against current Version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  home_assistant_current_install:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Copy stub files into configuration folder
        run: |
          cp -R ci_secrets.yaml secrets.yaml
          sudo mkdir -p /github/workspace/tmp
          HA_VERSION=$(<.HA_VERSION)
      - name: Install Home Assistant
        run: pip3 install homeassistant==$(cat .HA_VERSION)
      - name: Check config
        run: hass -c . --script check_config --info all
